name: "v CI/CD"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: . scripts/test
  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    env:
      V_ROOT: /tmp/v
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: . integration/install_specific_version
