name: "v CI/CD"

on:
  pull_request:
  push:
    branches:
      - main

env:
  GO_VERSION: '1.21'

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: . script/test.sh
  format:
    name: "Formatting check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: . script/format.sh
  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    env:
      V_ROOT: /tmp/v
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: . integration/install_specific_version.sh
